name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy-infra:
    name: Terraform Deploy Infra
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_name: "aws-karpenter"
      TF_VAR_region: "us-east-1"

    defaults:
      run:
        working-directory: infra/terraform

    steps:
      - name: Checkout code 
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ secrets.TARGET_AWS_ACCOUNT }}:role/${{ secrets.TERRAFORM_ROLE }}

      - name: Initialize and Plan Terraform
        run: |
          terraform init -input=false
          terraform plan -input=false

      - name: Apply Terraform
        run: terraform apply -auto-approve